name: Run CMake
description: "Runs CMake"
inputs:
  args:
    description: "Other arguments"
    required: false
    default: -D_7BIT_CONF_BUILD_TESTS:BOOL=true -D_7BIT_CONF_BUILD_EXAMPLES:BOOL=true
  build-type:
    description: "Build type"
    required: false
    default: Release
  toolchain:
    description: "Toolchain file"
    required: false
    default: build/Release/generators/conan_toolchain.cmake
  library-type:
    description: "Library type"
    required: false
    default: Static
  build-dir:
    description: "Build directory"
    required: true

runs:
  using: composite
  steps:
    - name: Configure CMake
      working-directory: ${{ inputs.build-dir }}
      run: cmake --preset conan-release -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} -D_7BIT_CONF_LIBRARY_TYPE=${{ inputs.library-type }} ${{ inputs.args }}
      shell: pwsh

    - name: Build
      working-directory: ${{ inputs.build-dir }}
      run: cmake --build --preset conan-release .
      shell: pwsh
