name: Run CMake
description: "Runs CMake"
inputs:
  args:
    description: "Other arguments"
    required: false
    default: -D_7BIT_CONF_BUILD_TESTS:BOOL=true -D_7BIT_CONF_BUILD_EXAMPLES:BOOL=true
  library-type:
    description: "Library type"
    required: false
    default: Static

runs:
  using: composite
  steps:
    - name: Configure CMake
      run: cmake --preset conan-release -D_7BIT_CONF_LIBRARY_TYPE=${{ inputs.library-type }} ${{ inputs.args }}
      shell: pwsh

    - name: Build
      run: cmake --build --preset conan-release
      shell: pwsh
