name: Run CMake
description: "Runs CMake"
inputs:
  install-dir:
    description: "Installation directory"
    required: true

runs:
  using: composite
  steps:
    - name: Install Conan
      uses: turtlebrowser/get-conan@v1.2

    - name: Set Proper Conan Profile
      uses: kanga333/variable-mapper@v0.3.0
      with:
        key: "${{ runner.os }}"
        map: |
          {
            "Linux":{
                "use_conan_profile":"linux-gcc-x86_64",
                "preset": "conan-release"
            },
            "macOS":{
                "use_conan_profile":"mac-appple-clang-x86_64",
                "preset": "conan-release"
            },
            "Windows":{
                "use_conan_profile":"windows-msvc-x86_64",
                "preset": "conan-default"
            }
          }
    - name: Configure Conan
      run: conan config install https://github.com/7bitcoder/conan-config.git
      shell: pwsh

    - name: Install Conan Packages in ${{ inputs.install-dir }}
      run: conan install . --output-folder=${{ inputs.install-dir }} --build=missing -pr=${{ env.use_conan_profile }} -pr:b=${{ env.use_conan_profile }}
      shell: pwsh

    - name: Set Preset
      id: set-preset
      run: |
        "PRESET=${{ env.preset }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh


