name: CI

on:
  push:
    branches: [ "dev", "main" ]
    paths-ignore:
      - ".readthedocs.yaml"
      - "README.md"

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        libraryType: [ HeaderOnly, Static, Shared ]
        os: [ ubuntu-22.04, macos-12, windows-2022 ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Conan Packages
        id: conan
        uses: ./.github/actions/conan-install
        with:
          install-dir: ${{ env.BUILD_DIR }}

      - name: CMake Build
        uses: ./.github/actions/cmake-build
        with:
          library-type: ${{ matrix.libraryType }}

      - name: Test
        run: ctest -j 10 --preset conan-release
